### PR TITLE
Node 6

### PR DESCRIPTION
**Pull request by jenius**
Upgrade to work only on node 6 and no longer require compilation via babel. Yay!

### CODE REVIEW

**Comment by kylemac** [comment]
LGTM 👍 🚀

**Comment by jenius** [comment]
I'm thinking we should have `app.js` not compiled with babel before shipping this. Yeah?

**Comment by kylemac** [comment]
i could go either way - i guess if we want to go all-the-way then, yes.

**Comment by jenius** [comment]
Yaaaa let'd do it all the way! Babel will just be for processing the front-end js

**Comment by jenius** [comment]
Ok so I'm going to ship this. Some pretty significant breaking changes, as we no longer support es6 modules in `app.js`, but that's why we're on patch versions!

**Comment by kylemac** [comment]
:shipit:

**Pull request merged**
