### PR TITLE
Allow postcss options to be passed through

### PR DESCRIPTION
**Pull request by jenius**
Because sometimes that's necessary

### CODE REVIEW

**Comment by kylemac** [comment]
our first breaking change?

**Comment by jenius** [comment]
Hah, I guess so! First of many for sure

**Comment by jenius** [comment]
I would like to put in tests for this, since it was not previously covered, but if you want to merge/ship I can do that for immediate use as well. Let me know!

**Comment by elvingm** [comment]
haha :+1: 
Yes, @jenius. If it's no problem to merge/ship now that'd be great. That way I'll keep pushing on this project with it

**Comment by jenius** [comment]
For sure, i'll do this in a moment :rocket:

**Pull request merged**
